<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Famiglia-in" nsURI="univaq.it/famiglia-in" nsPrefix="famiglia-in">
  <eClassifiers xsi:type="ecore:EClass" name="Persona" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nome" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Padre" eSuperTypes="#//Persona">
    <eStructuralFeatures xsi:type="ecore:EReference" name="famiglia" lowerBound="1"
        eType="#//Famiglia" eOpposite="#//Famiglia/padre"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Madre" eSuperTypes="#//Persona">
    <eStructuralFeatures xsi:type="ecore:EReference" name="famiglia" lowerBound="1"
        eType="#//Famiglia" eOpposite="#//Famiglia/madre"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Figlio" eSuperTypes="#//Persona">
    <eStructuralFeatures xsi:type="ecore:EReference" name="famiglia" lowerBound="1"
        eType="#//Famiglia" eOpposite="#//Famiglia/figli"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Figlia" eSuperTypes="#//Persona">
    <eStructuralFeatures xsi:type="ecore:EReference" name="famiglia" lowerBound="1"
        eType="#//Famiglia" eOpposite="#//Famiglia/figlie"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Famiglia">
    <eStructuralFeatures xsi:type="ecore:EReference" name="padre" lowerBound="1" eType="#//Padre"
        containment="true" eOpposite="#//Padre/famiglia"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="madre" lowerBound="1" eType="#//Madre"
        containment="true" eOpposite="#//Madre/famiglia"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="figli" upperBound="-1"
        eType="#//Figlio" containment="true" eOpposite="#//Figlio/famiglia"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="figlie" upperBound="-1"
        eType="#//Figlia" containment="true" eOpposite="#//Figlia/famiglia"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="indirizzo" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
